### ISSUE TITLE
Don't have access to the 'selectors' accessor.

### ISSUE THREAD

**Issue by nratter** [investtools/extensible-duck#10]
I don't have access to the 'selectors' accessor. I see it in 'options', but not directly on the duck instance.

![image](https://user-images.githubusercontent.com/3020810/29578417-3ae0109a-873d-11e7-9a5f-2be393619cdb.png)

On version 1.1.1

**Comment by aga5tya** [comment]
@nratter 1.1.1 on npm doesn't yet have the selectors change published yet. cc/ @akelmanson

**Comment by akelmanson** [comment]
Version 1.2.0 released!
