### ISSUE TITLE
Unable to import parts of the Duck

### ISSUE THREAD

**Issue by kbrandwijk** [investtools/extensible-duck#13]
I wanted to use the syntax `import { creators } from './MyDuck'`, but `creators` turns up `undefined`.
I can use `import MyDuck from './MyDuck'` and use `MyDuck.creators`, but it would be nice if I could only import the parts that I need (for example, only import `types` in my sagas, only import `creators` in my Containers, etc.

**Comment by akelmanson** [comment]
Hi @kbrandwijk 

extensible-duck cannot control what is exported by your js file, nevertheless you can do the following:

```js
const MyDuck = new Duck(...)
export default MyDuck
export const creators from MyDuck
```

**Comment by kbrandwijk** [comment]
@akelmanson Thank you. However, with `export default MyDuck`, and `creators` and `types` being properties on the Duck, `import { creators, types } from './MyDuck'` normally works. Is there anything special about the class that makes it return undefined?

**Comment by akelmanson** [comment]
@kbrandwijk Can you give me an example using a plain js object?
