### ISSUE TITLE
Add a new feature to manage Side Effects

### ISSUE THREAD

**Issue by jfreixa** [investtools/extensible-duck#18]
Add a new key to the object to manage the side effects(redux-saga, redux-thunk, redux-observables...).  Will be similar to "creators" but in a different key to having separated all the different logic.
I would like to know if this could be implemented in this library?

**Comment by zakol** [comment]
I've already implemented a redux-saga solution, will open a pull request late this week.

**Comment by james-cordeiro** [comment]
@zakol Have you opened up a PR yet on this? I can see there was one closed off submitted from yourself but I don't believe it's related to managing Side effects. Thanks

**Comment by akelmanson** [comment]
@zakol, are you there?

**Comment by mrfelton** [comment]
@zakol do you still plan to publish your redux-saga solution?

**Comment by akelmanson** [comment]
@zakol didn't answer, so I'm closing this issue.
