### ISSUE TITLE
Is there a new release coming?

### ISSUE THREAD

**Issue by dptoot** [investtools/extensible-duck#19]
Great library.  I have found it really useful.   I wondered if there is npm release coming?  I am seeing some features in the README that don't seem to be avaiable in the latest release v1.3.1.

- duck.storeaccessor doesn't seem available.   Only seems available from duck.options.
- constructLocalized isn't exported as demonstrated in the README

Thanks again!

**Comment by akelmanson** [comment]
Done! v1.4.0

**Comment by dptoot** [comment]
Awesome!  Thanks guys!
