### ISSUE TITLE
Couldn't find preset "latest" relative to directory

### ISSUE THREAD

**Issue by abeauvois** [investtools/extensible-duck#2]
Seems the .babelrc preset "latest" is stopping the transformation for React Native users.
By changing "latest" to "es2015" it works nicely, would it be possible for you to fix this ?

MacOS 
    "react": "15.5.4",
    "react-native": "0.42.3",
    "babel-core": "6.25.0",
    "babel-eslint": "6.1.2",
    "babel-jest": "19.0.0",
    "babel-loader": "6.4.1",
    "babel-plugin-inline-import": "2.0.5",
    "babel-preset-flow": "6.23.0",
    "babel-preset-react": "6.24.1",
    "babel-preset-react-native": "1.9.1",

Very nice approach of ducks BTW

**Comment by akelmanson** [comment]
Done! It's fixed on 1.0.1. Thanks for reporting the issue!
