### ISSUE TITLE
Allow constructLocalized  to provide localState of ducks store in deeply nested redux state trees

### ISSUE THREAD

**Issue by dptoot** [investtools/extensible-duck#22]
It seems that constructLocalized and all of the examples assume that the  structure of the final redux state to flattened.  
      
We have found that ducks and traditional reducers can live together and that has presented occurences where the ducks store instance is bound deeply within the redux store.   constructLocalized is unable to locate this state and then in turn unable to provide it to the  selectors.

I'd like to  propose the addition of a new option ```storePath``` that would allow an instance to define its final location within the redux state.

**Comment by akelmanson** [comment]
Thank you for your contribution!

**Comment by akelmanson** [comment]
https://www.npmjs.com/package/extensible-duck/v/1.5.0
