### ISSUE TITLE
[Discussion] Add selectors as part of Duck instance

### ISSUE THREAD

**Issue by aga5tya** [investtools/extensible-duck#5]
How about state selectors also be part of the instance so we could easily share the selectors and access the state within. Similar to another implementation i saw here https://github.com/cyrilluce/saga-duck.

Let me know your thoughts :) @akelmanson

**Comment by akelmanson** [comment]
Hi aga5ty. I've never used selectors but I think it makes a lot of sense to include support in extensible-duck. You are welcome to submit a PR!

**Comment by akelmanson** [comment]
Thank you, @aga5tya!
