### ISSUE TITLE
Remove lodash dependency.

### ISSUE THREAD

**Issue by aga5tya** [investtools/extensible-duck#7]
Lodash lib seems to pull in alot of other code for the used methods. For the use cases in this library, we could eliminate the usage of lodash altogether replacing them with vanilla es6 methods.

This further reduces the final gzipped size down by approx 70% (final 1kb approx) and non-gzipped around 60%. 🎉  Win for web bundles. 👍 

I have been using the version with lodash removed and haven't found any issues, let me know your thoughts @akelmanson. If all fine, il create a PR post investtools/extensible-duck/pull/6

https://github.com/aga5tya/extensible-duck/tree/remove-underscore

**Comment by akelmanson** [comment]
Awesome! I'll review it in the next days.

**Comment by akelmanson** [comment]
Submit the PR, please!

**Comment by aga5tya** [comment]
@akelmanson, please review the PR when you have time :)

**Comment by akelmanson** [comment]
@aga5tya thank you for your contribution!
