### ISSUE TITLE
redux-thunk support

### ISSUE THREAD

**Issue by Gregor1971** [investtools/extensible-duck#8]
It works, which is great, so it might be worth adding to the README:

A Duck's action creators can be normal plain objects or thunks (see: [redux-thunk](https://github.com/gaearon/redux-thunk))
```js
    creators: (duck) => ({
        logout:             () => ({ type: duck.types.LOGOUT }),
        removeTokenAsync:   () => {
                return dispatch => {
                    return StorageAsync.removeItem(tokenKey)
                    .then(() => (dispatch({ type: duck.types.REMOVE_TOKEN })));
                }
        }
    })
```

**Comment by akelmanson** [comment]
Done! Sorry for the delay.

https://github.com/investtools/extensible-duck#defining-the-creators
